### ISSUE TITLE
Retrive All Pulses

### ISSUE THREAD

**Issue by npormambi** [AlienVault-Labs/OTX-Python-SDK#25]
Hello All,

As per Dashboard there are more that 4000 Pulses, but when I try to fetch all the pulses with below code
pulses = otx.getall(), I am able to fetch around 250 pulses only.

Does anyone knows how to fetch all the pulse in one go.
 

Thanks and Regards.

**Comment by jaimeblasco** [comment]
@npormambi You only retrieve the pulses you are subscribed to.

**Comment by jaimeblasco** [comment]
or the pulses from the accounts you are subscribed to

**Comment by npormambi** [comment]
Thanks @jaimeblasco  
But at the moment I havent subscribe to any pulses.
At the moment there are 6000 pulses.
How can I retrieve all in one go or is there any other way with which I can atleast get new pulses without subscribing.
Or using API

**Comment by jaimeblasco** [comment]
@npormambi The system is not designed to work that way. The information you can download using the API is limited to the accounts and pulses you follow. For instance, once you create an account you are subscribed to the AlienVault account by default. It means that using the API you will be able to retrieve all the pulses that the AV account has created.

**Comment by npormambi** [comment]
@jaimeblasco  Thanks a lot, Got the info I needed.
