### ISSUE TITLE
feature request: ability to submit threat indicators

### ISSUE THREAD

**Issue by mwollenweber** [AlienVault-Labs/OTX-Python-SDK#4]
As a feature request it would be beneficial to submit threat indictors via an API rather than only requesting.

**Comment by mcm** [comment]
+1 for this, I'm not sure whether the API supports this but I've been trying to figure out who to get in contact with to request this feature. I'd be happy to help implement however I can if such a feature can be added.

**Comment by alaaalii** [comment]
Feature was added in commit https://github.com/AlienVault-Labs/OTX-Python-SDK/commit/54bce81bd5285c9f336be7182516ae721e11a050. The method is `create_pulse`.
