### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sebix** [AlienVault-Labs/OTX-Python-SDK#5]
No license for this project has been defined, thus it is copyrighted by default. Therefore the code cannot be used by other project without violating copyright laws!

**Comment by adulau** [comment]
I have the exact same question, it would be great if this could be clarified. A 2-clause BSD license would be really nice.

**Comment by jaimeblasco** [comment]
I have added a LICENSE file. Thanks for pointing this out! @sebix @adulau
