### ISSUE TITLE
Python not book does not show where to set the API key

### ISSUE THREAD

**Issue by rayschippers** [AlienVault-Labs/OTX-Python-SDK#7]
The python notebook says to replace YOUR_KEY with your actual API key. It doesnt say anywhere where to specify the key.

**Comment by jaimeblasco** [comment]
@rayschippers Do you mean where to find the key?. That would be https://otx.alienvault.com/settings/

**Comment by rayschippers** [comment]
I mean, in the documentation it says otx = OTXv2("") in the code snippet
and below that it states replace YOUR_KEY with your API Key found at ......
The code snippet should read otx = OTXv2("YOUR_KEY")

**Comment by lillypad** [comment]
I can confirm this is still an issue in 2017 and Alien Vault hasn't fixed this or seems to indicate or record any other documentation on their Python API anywhere on the web. Their site is going well but did they abandon this whole project? If you make an SDK you would expect the documentation to be longer than one page and incomplete at that...

**Comment by bsmartt13** [comment]
@lillypad are you unable to use OTX-Python-SDK?  This is a documentation issue and the fix is noted above:

```otx = OTXv2("YOUR_KEY")```

I submitted a PR to fix the documentation.

**Comment by lillypad** [comment]
I know, just seems odd they haven't merged it yet in literally 2 years...

**Comment by rspitler-alien** [comment]
With @bsmartt13 pull hopefully this is clarified.  In addition I added a link to the live API documentation hosted in the site for more clarity on the contents of the API calls.
